network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_post", views.new_post, name="new_post"),

    #API's
    path("all_posts", views.all_posts, name="all_posts"),
    path("load_profile/<str:user>", views.load_profile, name="load_profile"),
    path("get_foll/<str:user>", views.get_foll, name="get_foll"),
    path("following/<int:to_follow>", views.following, name="following"),
    path("follow_or_un", views.follow_or_un, name="follow_or_un")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    followers = models.IntegerField(default=0)
    followed = models.IntegerField(default=0)
    def serialize(self):
        return {
            "followers": self.followers,
            "followed": self.followed
            

        }
  

class UserPosts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="poster")
    post = models.CharField(max_length=280)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def serialize(self):
        return {
            "id": self.id,
            "Post": self.post,
            "Posted": self.timestamp.strftime("%b %d %Y, %I:%M %p"),
            "likes": self.likes,
            "user": self.user.username

        }
  

class Following(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follows")

    def serialize(self):
        return {
            "user": self.user,
            "following": self.following,
            

        }

network/forms.py
from django import forms

class NewPostForm(forms.Form):
    post = forms.CharField(label="New Post")

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import NewPostForm
from django.http import JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import User, UserPosts, Following


def index(request):
    return render(request, "network/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

def new_post(request):
    if request.method == "POST":
        user = request.user
        form = NewPostForm(request.POST)
        if form.is_valid():
            # Get data from form
            # Argument in [] HAS to be form element name!!
            post = form.cleaned_data["post"]
            new_post = UserPosts.objects.create(user=user, post=post)
            new_post.save()
            return render(request, "network/index.html", {
        "form":NewPostForm()
    })
        
    
    return render(request, "network/new_post.html", {
        "form":NewPostForm()
    })

def all_posts(request):
    # user = request.user
    posts = UserPosts.objects.all()
    
    posts = posts.order_by("-timestamp").all()
    
    return JsonResponse([post.serialize() for post in posts], safe=False)
    

@login_required()
def load_profile(request, user):
    user = User.objects.get(username=user)
    profile_content = UserPosts.objects.filter(user=user.id)
    add_id = [post.serialize() for post in profile_content]
    add_id.append({'user_id':user.id})
    return JsonResponse(add_id, safe=False)
    # return JsonResponse(all_cont, safe=False)


@login_required()
def get_foll(request, user):
    num_of_foll = User.objects.filter(username=user)
    return JsonResponse([foll.serialize() for foll in num_of_foll], safe=False)

@csrf_exempt
@login_required()
def following(request, to_follow):
    followed = User.objects.get(username=request.user)
    if request.method == "PUT":
        
        toFollow = User.objects.get(id=to_follow)
        
        try:
            following = Following.objects.get(user=request.user, following=toFollow)
            print("delete")

            followed.followed = followed.followed - 1
            followed.save()

            followers = User.objects.get(username=toFollow)
            followers.followers = followers.followers - 1
            followers.save()
            # following.user.following
            following.delete()


            return render(request, "network/index.html")
        except:
            #Add new follower to follower model
            new_follower = Following.objects.create(user=request.user, following=toFollow)
            new_follower.save()

            #Update the user who followed's follwed amount in User
            
            followed.followed = followed.followed + 1
            followed.save()

            #Update the user being followed's followers
            followers = User.objects.get(username=toFollow)
            followers.followers = followers.followers + 1
            followers.save()

            return HttpResponse(status=204)
    if request.method == "GET":
        followers = Following.objects.filter(user_id=request.user)
        follower_posts = []
        for follower in followers:
            follower_posts.append(UserPosts.objects.filter(user_id=follower.following_id))
        allp = []
        for i in follower_posts:
            i = i.order_by("-timestamp").all()
            for j in i:
                allp.append(j)
        
        return JsonResponse([foll.serialize() for foll in allp], safe=False)
    return None
  
def follow_or_un(request):
    is_following = Following.objects.filter(user_id=request.user)
    fol = [i.following.username for i in is_following]
    return JsonResponse(fol, safe=False)

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}




{% if user.is_authenticated %}
<div id="new-post">
    
    <h3>New Post</h3>
    <form action="/new_post" id="post-form" method="post">
        {% csrf_token %}
            <label>New Post:</label>
            <div class="element">
                <input type="text" name="post" required="" id="id_post">
            </div>
        
        
        <input type="submit" class="btn btn-primary">
    </form>
    
</div>

<div id="profile">
    <h1>Profile</h1>
</div>

<div id="peopleFollowed">
    <div class="title_div">
        <h1 class="title">Following</h1>
    </div>
</div>

{% endif %}


<div id="all-posts">
    <h1>All posts</h1>
</div>



{% endblock %}

{% block script %}
    <script src="{% static 'network/net.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li data-name="{{ user.username }}"  class="username" class="nav-item">
                    <a class="nav-link" href="#"><strong id="cur_user" >{{ user.username }}</strong></a>
                </li>
            

                <li id="newpost" class="nav-item">
                    <a class="nav-link" href="#">New Post</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  
                  <a id="allposts" class="nav-link" href="#">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a data-user={{ user.id }} id="followers" class="nav-link" href="#">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

{% block script %}
    <script src="{% static 'network/net.js' %}"></script>
{% endblock %}

network/templates/network/new_post.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

{% if user.is_authenticated %}
<div id="new-post">
    <h3>New Post</h3>
    <form action="{% url 'new_post' %}" id="post-form" method="post">
        {% csrf_token %}
        {% for element in form %}
            {{ element.label_tag }}
            <div class="element">
                {{ element }}
            </div>
        {% endfor %}
        
        <input type="submit" class="btn btn-primary"/>
    </form>
</div>
{% endif %}

<div id="all-posts">
    
</div>


{% endblock %}

{% block script %}
    <script src="{% static 'network/net.js' %}"></script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

{% block script %}
    <script src="{% static 'network/net.js' %}"></script>
{% endblock %}